#MOLGENIS walltime=23:59:00 mem=4gb ppn=1
# worksheet params:
#string tmpName
#string project
#string logsDir
#list externalSampleID
#list lane
#list flowcell
#list batchID
#string contact

# conststants
#string qcStatisticsCsv
#string projectQcDir
#string getStatisticsScript
#string getDedupInfoScript
#string qcStatisticsTex
#string qcStatisticsDescription
#string qcDedupMetricsOut
#string qcBaitSet
#string qcStatisticsTexReport
#string qcReportMD
#string allRawArrayTmpDataDir
#string intermediateDir
#string inSilicoConcordanceFile
#string allMetrics 

#string bwaVersion
#string computeVersion
#string cutadaptVersion
#string dbNSFPVersion
#string dellyVersion
#string fastqcVersion
#string gatkVersion
#string hpoVersion
#string javaVersion
#string molgenisAnnotatorVersion
#string ngsUtilsVersion
#string ngsversion
#string picardVersion
#string pythonVersion
#string rVersion
#string sambambaVersion
#string samtoolsVersion
#string snpEffVersion
#string tabixVersion
#string wkHtmlToPdfVersion


module load ${wkHtmlToPdfVersion}
module load ${rVersion}
module load ${ngsUtilsVersion}
module load ${ngsversion}

#
## Define bash helper function for arrays
#

array_contains () { 
    local array="$1[@]"
    local seeking=$2
    local in=1
    for element in "${!array-}"; do
        if [[ "$element" == "$seeking" ]]; then
            in=0
            break
        fi
    done
    return $in
}
if [ -f ${allMetrics} ] 
then
	rm ${allMetrics}
fi

#This check needs to be performed because Compute generates duplicate values in array
INPUTS=()
for SampleID in "${externalSampleID[@]}"
do
        array_contains INPUTS "$SampleID" || INPUTS+=("$SampleID")    # If bamFile does not exist in array add it
done

#folded only on uniq externalSampleIDs
for sample in "${INPUTS[@]}"
do
	echo -e "$intermediateDir/${sample}.total.qc.metrics.table" >> ${allMetrics}
done

if [ "${contact}" == "" ]
then
	contact="Cleo C. van Diemen (c.c.van.diemen@umcg.nl)"
fi


cat > ${intermediateDir}/${project}_QCReport.rhtml <<'_EOF'
<html>
<head>
  <title>${project} QCReport</title>
</head>
<style type="text/css">
      div.page {
        page-break-after: always;
        padding-top: 60px;
        padding-left: 40px;
	td: padding: 6px;
      }
</style>
<body style="font-family: monospace;">

<div class="page" style="text-align:center;">
<font STYLE="font-size: 45pt;">
<br>
<br>
<br>
<br>
<br>
<br>
  <b>Next Generation Sequencing report</b>
</font>
<font STYLE="font-size: 30pt;">
<br>
<br>
<br>
<br>
  Genome Analysis Facility (GAF), Genomics Coordination Centre (GCC)
<br>
<br>

  University Medical Centre Groningen
<script language="javascript">
        var month=new Array(12);
        month[0]="January";
        month[1]="February";
        month[2]="March";
        month[3]="April";
       month[4]="May";
        month[5]="June";
        month[6]="July";
        month[7]="August";
        month[8]="September";
        month[9]="October";
        month[10]="November";
        month[11]="December";
        var currentTime = new Date()
        var month =month[currentTime.getMonth()]
        var day = currentTime.getDate()
        var year = currentTime.getFullYear()
  document.write(month + " " + day + ", " + year)
</script>

<div style="text-align:left;">
<br>
<br>
<br>
<br>
<table align=center STYLE="font-size: 30pt; border-spacing: 8px 2px;">
        <tr>
            	<td><b>Report</b></td>
        </tr>
	<tr>
            	<td>Created on</td>
                <td>
<script language="javascript">
        var month=new Array(12);
        month[0]="January";
        month[1]="February";
        month[2]="March";
        month[3]="April";
        month[4]="May";
        month[5]="June";
        month[6]="July";
        month[7]="August";
        month[8]="September";
        month[9]="October";
        month[10]="November";
        month[11]="December";
        var currentTime = new Date()
        var month =month[currentTime.getMonth()]
        var day = currentTime.getDate()
        var year = currentTime.getFullYear()
  document.write(month + " " + day + ", " + year)
</script>
                </td>
        </tr>
        <tr>
                <td>Generated by</td><td>GAF, GCC, UMCG</td>
        </tr>
        <tr></tr><td></td>
        <tr>
                <td><b>Project</b></td>
        </tr>
        <tr>
                <td>Project name</td><td>${project}</td>
        </tr>
	<tr>
		<br />
	</tr>
	<tr>
            	<td>Number of samples</td>
		<td>
		<!--begin.rcode, engine='bash', echo=FALSE, comment=NA, warning=FALSE, message=FALSE, results='asis'
		cat ${allMetrics} | wc -l	
		end.rcode-->
		</td>
	</tr>
	<tr>
            	<td>Pipeline version</td><td>${ngsversion}</td>
        </tr>
	<tr>
		<br />
	</tr>
        <tr>
            	<td><b>Contact</b></td>
        </tr>
	<tr>
            	<td>Name</td>
		<td>
			${contact}
		</td>
        </tr>
</table>
</div>
</div>
</p>

<div class="page">
<p>
<h1>Introduction</h1>
<br>
<br>
<pre>
This report describes a series of statistics about your sequencing data. Together with this
report you'll receive alignment files. If you, in addition, also want
the raw data, then please notify us via e-mail. In any case we'll delete the raw data,
three months after</pre> <script language="javascript">
        var month=new Array(12);
        month[0]="January";
        month[1]="February";
        month[2]="March";
        month[3]="April";
        month[4]="May";
        month[5]="June";
        month[6]="July";
        month[7]="August";
        month[8]="September";
        month[9]="October";
        month[10]="November";
        month[11]="December";
        var currentTime = new Date()
        var month =month[currentTime.getMonth()]
        var day = currentTime.getDate()
        var year = currentTime.getFullYear()
  document.write(month + " " + day + ", " + year)
</script>
<pre>

Used toolversions:

${bwaVersion}
Molgenis-Compute/${computeVersion}
cutadapt-${cutadaptVersion}
dbNSFP-${dbNSFPVersion}
delly/${dellyVersion}
${fastqcVersion}
${gatkVersion}
${javaVersion}
${ngsUtilsVersion}
${picardVersion}
${pythonVersion}
${rVersion}
${sambambaVersion}
${samtoolsVersion}
${snpEffVersion}
${tabixVersion}
${molgenisAnnotatorVersion}
hpoVersion: ${hpoVersion}
</pre>
<div>
<!--begin.rcode, engine='python', echo=FALSE, comment=NA, warning=FALSE, message=FALSE, results='asis'
# print out tables with QC stats based on the qcMatricsList

import csv

with open("${allMetrics}") as f:
    files = f.read().splitlines()

titles = []
arrayValues = []
isFirst = 'true'

for file in files:

    with open(file,'r') as f:
        reader = csv.reader(f, delimiter='\t')

        values = []

        for row in reader:
            if(len(row) > 1):
                if(isFirst == 'true'):
                    titles.append(row[0])
                values.append(row[1])

        arrayValues.append(values)
        isFirst = 'false'

filesNumber = len(arrayValues)
index = len(titles)

arrayResults = []

tableNumbers = int(len(arrayValues) /3)

count = 0

for j in range(0, filesNumber):
    if(count == 0):
        results = []
        for i in range(0, index):
            results.append('')
    for i in range(0, index):
        results[i] += arrayValues[j][i].ljust(30)
    count += 1
    if(count == 3):
        count = 0
        arrayResults.append(results)
    elif(j == filesNumber - 1):
        arrayResults.append(results)

arraySize = len(arrayResults)

print('<h1>Project analysis results</h1>')

for j in range (0, arraySize):
    print('<div class="page"><h2 style="text-align:center">Table ' + str(j+1) +': Overview statistics</h2></br><pre>')
    ress = arrayResults[j]
    for i in range(0, index):
        print(titles[i].ljust(60) + ress[i].ljust(30))
    print('</pre></div>')

end.rcode-->
</div>
</font>
</html>
_EOF

echo "generate QC report."
# generate HTML page using KnitR
R -e 'library(knitr);knit("${intermediateDir}/${project}_QCReport.rhtml","${projectQcDir}/${project}_QCReport.html")'

#remove border
sed -i 's/border:solid 1px #F7F7F7/border:solid 0px #F7F7F7/g' ${projectQcDir}/${project}_QCReport.html

#
## Initialize
#
mkdir -p ${projectQcDir}
mkdir -p ${projectQcDir}/images

#only available with PE
if [ -f "${intermediateDir}/*.merged.dedup.bam.insert_size_metrics" ]
then
	cp ${intermediateDir}/*.merged.dedup.bam.insert_size_histogram.pdf ${projectQcDir}/images
    	cp ${intermediateDir}/*.merged.dedup.bam.insert_size_metrics ${projectQcDir}/images
fi

#convert to pdf

wkhtmltopdf-amd64 --page-size A0 ${projectQcDir}/${project}_QCReport.html ${projectQcDir}/${project}_QCReport.pdf

